version: "3"
services:
  cerbot_enabler:
    container_name: "cerbot_enabler"
    image: nginx:1.21.1-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx/config/enabler.conf:/etc/nginx/conf.d/default.conf
      - ./letsencrypt:/etc/letsencrypt:ro
      - /tmp/acme-challenge:/tmp/acme-challenge
    networks:
      - enabler
    restart: always

networks:
  enabler:
    driver: bridge